// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include <iostream>

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/fl_draw.H>

/**
 * 自定义一个窗口
 */
class Win : public Fl_Double_Window
{
public:
    Win(int x, int y, int w, int h, const char *label = 0) : Fl_Double_Window(x, y, w, h, label)
    {
        init();
    }
    Win(int w, int h, const char *label = 0) : Fl_Double_Window(w, h, label)
    {
        init();
    }

    void init()
    {
        // 背景色为白色
        color(FL_WHITE);
        // 无边框
        box(FL_FLAT_BOX);
    }

    /**
     * 重写 draw 函数
     */
    virtual void draw()
    {
        // 调用父类 draw 函数
        Fl_Double_Window::draw();

        // 绘制一条黑色的线
        fl_color(FL_BLACK);
        fl_line(10, 10, 50, 50);
    }
};

/**
 * 窗口居中显示
 */
static void make_window_center(Fl_Double_Window *win)
{
    // 获取屏幕寬高
    int screen_w = Fl::w();
    int screen_h = Fl::h();

    // 窗口寬高
    int win_w = win->w();
    int win_h = win->h();

    // 计算位置
    int x = (screen_w - win_w) / 2;
    int y = (screen_h - win_h) / 2;

    // 设置位置
    win->position(x, y);
}

int main(int argc, char **argv)
{
    Fl_Double_Window *w;
    Win *win = new Win(366, 261, "FLTK - 绘图");
    w = win;
    win->end();
    win->resizable(win);

    // 窗口居中
    make_window_center(w);

    w->show(argc, argv);
    return Fl::run();
}
